SELECT
    dv.APPROVAL_STATUS,
    dv.ARCHIVE_FLAG,
    dv.REMOVED_FLAG,
    COUNT(*) AS cnt
FROM 
    [PrismFlightSafety_SQL].[dbo].[DOCUMENT_LOCATORS] AS dl
    INNER JOIN [PrismFlightSafety_SQL].[dbo].[DOCUMENT_VERSIONS] AS dv
        ON dl.DOCUMENT_ID = dv.DOCUMENT_ID
        AND dl.VERSION    = dv.VERSION
WHERE 
    dl.DOCUMENT_FILE    IS NOT NULL
    AND dl.DOCUMENT_CONTENT IS NOT NULL
GROUP BY 
    dv.APPROVAL_STATUS, dv.ARCHIVE_FLAG, dv.REMOVED_FLAG
ORDER BY 
    cnt DESC