SELECT
    CASE WHEN DOCUMENT_LINK    IS NOT NULL THEN 1 ELSE 0 END AS has_link,
    CASE WHEN DOCUMENT_FILE    IS NOT NULL THEN 1 ELSE 0 END AS has_file,
    CASE WHEN DOCUMENT_CONTENT IS NOT NULL THEN 1 ELSE 0 END AS has_content,
    CASE WHEN DOCUMENT_KEY     IS NOT NULL THEN 1 ELSE 0 END AS has_key,
    COUNT(*)                                                  AS cnt
FROM 
    [PrismFlightSafety_SQL].[dbo].[DOCUMENT_LOCATORS]
GROUP BY
    CASE WHEN DOCUMENT_LINK    IS NOT NULL THEN 1 ELSE 0 END,
    CASE WHEN DOCUMENT_FILE    IS NOT NULL THEN 1 ELSE 0 END,
    CASE WHEN DOCUMENT_CONTENT IS NOT NULL THEN 1 ELSE 0 END,
    CASE WHEN DOCUMENT_KEY     IS NOT NULL THEN 1 ELSE 0 END
ORDER BY 
    cnt DESC